
FROM maven:3.9.12-eclipse-temurin-25-alpine AS build

WORKDIR /app
COPY . .
RUN ./mvnw package -DskipTests

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=build /app/target/quarkus-app /app/

EXPOSE 8080
CMD ["java", "-jar", "quarkus-run.jar"]
